### ISSUE TITLE
I'm receiving a stream.on is not a function error

### ISSUE THREAD

**Issue by micahblu** [sindresorhus/gulp-imagemin#168] opened 2016-05-03 22:12 UTC
I have a sample project with 4 images in it and the following in my gulpfile.js:

```js
const gulp = require('gulp');
const imagemin = require('gulp-imagemin');
const pngquant = require('imagemin-pngquant');
 
gulp.task('default', () => {
	return gulp.src('./images/*')
		.pipe(imagemin({
			progressive: true,
			svgoPlugins: [{removeViewBox: false}],
			use: [pngquant()]
		}))
		.pipe(gulp.dest('dist/images'));
});
```
when running `gulp` I get the following output:

```shell
/home/micah/Projects/test-images/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:740
  stream.on('end', function () {
         ^

TypeError: stream.on is not a function
    at Readable.wrap (/home/micah/Projects/test-images/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:740:10)
    at wrap (/home/micah/Projects/test-images/node_modules/stream-combiner2/index.js:67:29)
    at combine (/home/micah/Projects/test-images/node_modules/stream-combiner2/index.js:29:18)
    at Function.module.exports.obj (/home/micah/Projects/test-images/node_modules/stream-combiner2/index.js:22:10)
    at Imagemin.createStream (/home/micah/Projects/test-images/node_modules/imagemin/index.js:103:24)
    at Imagemin.run (/home/micah/Projects/test-images/node_modules/imagemin/index.js:77:20)
    at DestroyableTransform.through.obj.percent (/home/micah/Projects/test-images/node_modules/gulp-imagemin/index.js:56:12)
    at DestroyableTransform._transform (/home/micah/Projects/test-images/node_modules/through2-concurrent/through2-concurrent.js:29:15)
    at DestroyableTransform.Transform._read (/home/micah/Projects/test-images/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/micah/Projects/test-images/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
```
Here's the test repo I'm using. I appreciate any help.

https://github.com/micahblu/test-gulp-imagemin

**Comment by shinnn** [comment] 2016-05-03 23:11
Exact duplicate of https://github.com/sindresorhus/gulp-imagemin/issues/167.

**Closed by shinnn** 2016-05-03 23:11 UTC

**Comment by micahblu** [comment] 2016-05-03 23:12
My apologies~!
