### ISSUE TITLE
node_modules/jpegtran-bin/vendor/jpegtran ENOENT

### ISSUE THREAD

**Issue by jeroenb2511** [sindresorhus/gulp-imagemin#160] opened 2016-02-16 09:32 UTC
What do I wrong?

Node 5.6.0
NPM 3.7.2
imagemin 2.4.0

events.js:154
throw er; // Unhandled 'error' event
^
Error: spawn /Users/jeroen/Documents/Development/Suz/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
at exports._errnoException (util.js:856:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
at onErrorNT (internal/child_process.js:344:16)
at nextTickCallbackWith2Args (node.js:475:9)
at process._tickCallback (node.js:389:17)

**Comment by shinnn** [comment] 2016-02-16 09:37
Duplicate of https://github.com/imagemin/imagemin/issues/154

**Closed by shinnn** 2016-02-16 09:37 UTC
