### ISSUE TITLE
Moves & compresses everything but JPG

### ISSUE THREAD

**Issue by philliprauschkolb** [sindresorhus/gulp-imagemin#170] opened 2016-05-06 18:48 UTC
This is working great aside from it not copying any of my JPG files for some reason. 

In my gulpfile.js:
`gulp.task('images', function(){`
`    return gulp`
`        .src(config.images)`
`        .pipe($.imagemin())`
`        .pipe(gulp.dest(config.build + 'images'));`
`});`

Moves GIF, PNG, SVG as expected, but ignores JPG

**Comment by kevva** [comment] 2016-05-06 19:38
Does it say something when using `verbose: true`?

**Comment by philliprauschkolb** [comment] 2016-05-06 21:02
No errors, just lists the files that it did work for:

`[14:00:06] gulp-imagemin: ✔ AngularJS-small.png (saved 515 B - 16.4%)`
`[14:00:06] gulp-imagemin: ✔ busy.gif (already optimized)`
`[14:00:06] gulp-imagemin: ✔ photos/anant-narayanan.png (saved 374 B - 2.3%)`
`[14:00:06] gulp-imagemin: ✔ photos/ben-teese.png (saved 5.65 kB - 48.6%)`
`[14:00:06] gulp-imagemin: ✔ photos/ben-clinkinbeard.png (saved 316 B - 1.9%)`
`[14:00:06] gulp-imagemin: ✔ photos/ari-lerner.png (saved 305 B - 1.8%)`
`[14:00:06] gulp-imagemin: ✔ photos/dave-smith.png (saved 385 B - 3.4%)`
`[14:00:06] gulp-imagemin: ✔ photos/christian-lilley.png (saved 330 B - 2.3%)`
`[14:00:06] gulp-imagemin: ✔ photos/burke-holland.png (saved 408 B - 3.1%)`
`[14:00:06] gulp-imagemin: ✔ photos/brian-ford.png (saved 2.73 kB - 15.9%)`
`[14:00:07] gulp-imagemin: ✔ gulp-tiny.png (saved 2.54 kB - 15.7%)`

**Comment by sindresorhus** [comment] 2016-05-08 06:03
Can you ensure you're using the latest version of `gulp-imagemin` by reinstalling? Then try a random JPG image from the internet and see if you still encounter the problem?

**Comment by axelingadi** [comment] 2016-05-08 10:40
Having the same problem. It skips all Jpg files

**Comment by axelingadi** [comment] 2016-05-08 15:06
Works great but it skips jpg files. Seems this is a problem with the recent version 3.0.0 release. Reverted to version 2.4.0 which works fine.
**Version 3.0.0**
![screenshot from 2016-05-08 17 58 49](https://cloud.githubusercontent.com/assets/6121225/15098468/671deb14-1547-11e6-908c-aefae18314eb.png)
**Version 2.4.0**
![screenshot from 2016-05-08 17 53 12](https://cloud.githubusercontent.com/assets/6121225/15098474/7fd2acee-1547-11e6-8c37-0b23e67bb19f.png)

**Comment by jaycom** [comment] 2016-05-09 10:01
I have this issues too, in ver 3.0.0,
Use 2.4.0 that is no problem

**Comment by kevva** [comment] 2016-05-09 11:01
It's most likely due to mozjpeg failing to install correctly.

**Comment by philliprauschkolb** [comment] 2016-05-09 15:48
Reverting to 2.4.0 did fix the issue for me

**Comment by maranomynet** [comment] 2016-05-16 11:32
I'm using version 3.0.1.
It processes JPGs with the defaults options, but as soon as I add a custom `jpegtran` option throws an "only one input file" error on the first JPG file and aborts the task.

```js
.pipe( imagemin([
    imagemin.jpegtran({ progressive: true })
]) )
```
Also, when I try to switch to use imagemin-mozjpeg instead...

```js
var mozjpeg = require('imagemin-mozjpeg');
// ...
```js
.pipe( imagemin([
    mozjpeg({ progressive: true })
]) )
```

It fails with this error:

```
dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /path-to-my/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found
```

Using node 5.11.1 / npm 3.8.6

**Comment by Nirazul** [comment] 2016-05-16 20:26
I'm having the same issue as @maranomynet 
Everything's fine as long as I don't have any custom config. When adding `{ progressive: true }` I'm getting the same error.

**Comment by maranomynet** [comment] 2016-05-16 20:54
Some sort of warning should be issued, against upgrading to version 3.

**Comment by Nirazul** [comment] 2016-05-16 21:01
To be fair, semver major jumps come with breaking changes. And a warning was placed in the [release notes](https://github.com/sindresorhus/gulp-imagemin/releases/tag/v3.0.0).
Anyway, this looks like a separate issue.

@maranomynet Maybe you could open a new ticket for the issue to be confirmed by sindre?

**Comment by maranomynet** [comment] 2016-05-16 21:59
Breaking change != Broken change.

**Comment by Nirazul** [comment] 2016-05-17 06:37
@maranomynet 
Yeah, you're right. But I don't think that this was intended ;)
I've tried out `imagegmin-jpeg-recompress` after the standard compiler failed and it works fine.

**Comment by maranomynet** [comment] 2016-05-17 09:32
gulp-imagemin@2.4.0 + imagemin-mozjpeg@5.0.0 also seems to be a combo that works. Suspect I'll be sticking with that for a while.

imagemin-mozjpeg@5.1.0+ seem to "work" mostly in theory on OSX, as those versions point to a buggy/broken version of the core mozjpeg library, and require a fairly obscure compiler update procedure before working consistently across installs.

**Comment by kevva** [comment] 2016-05-18 11:25
This should be fixed now (see https://github.com/imagemin/imagemin-jpegtran/commit/b9a3d2316bc8400687dfd8b38d33a80aa2e29acc). The arguments was added in the wrong order causing `jpegtran` to fail.

**Closed by kevva** 2016-05-18 11:25 UTC
