### ISSUE TITLE
TypeError: pPipe(...) is not a function

### ISSUE THREAD

**Issue by Antoder10** [sindresorhus/gulp-imagemin#327] opened 2019-05-27 20:58 UTC
**Configuration**

- `gulp` v3.9.1
- `gulp-imagemin` v5.0.3

**Message**
```
TypeError: pPipe(...) is not a function

    at Function.module.exports.buffer (C:\Users\Antonio\Desktop\V2\node_modules\imagemin\index.js:71:31)
    at DestroyableTransform.through.obj (C:\Users\Antonio\Desktop\V2\node_modules\gulp-imagemin\index.js:75:12)
    at DestroyableTransform._transform (C:\Users\Antonio\Desktop\V2\node_modules\through2-concurrent\through2-concurrent.js:34:15)
    at DestroyableTransform.Transform._read (C:\Users\Antonio\Desktop\V2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\Antonio\Desktop\V2\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\Antonio\Desktop\V2\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\Antonio\Desktop\V2\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\Users\Antonio\Desktop\V2\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at write (C:\Users\Antonio\Desktop\V2\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\Antonio\Desktop\V2\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
```

**gulpfile.js**
```
const gulp = require('gulp'),
rename = require("gulp-rename"),
imagemin = require('gulp-imagemin'),
imageminWebp = require('imagemin-webp');

gulp.task('images', () =>
    gulp.src('src/img/*')
    .pipe(imagemin(['img/*.{jpg,png}'], {
        use: [
            imageminWebp({quality: 50})
        ]
    }))
    .pipe(imagemin(['img/*.svg']))
    .pipe(rename(['img/*.{jpg,png}'], { extname: '.webp' }))
    .pipe(gulp.dest('dist/img\'))
);
```

**Comment by sindresorhus** [comment] 2019-05-30 10:26
Duplicate of #326

**Closed by sindresorhus** 2019-05-30 10:26 UTC
