### ISSUE TITLE
Cannot install gulp-imagemin -- Invalid non-string/buffer chunk

### ISSUE THREAD

**Issue by tkdan235** [sindresorhus/gulp-imagemin#144] opened 2015-10-16 23:22 UTC
I am running OSX 10.10.5 with node v4.1.1 and npm 2.14.4.

If I try to install gulp-imagemin I get the following output:

```
➜  example  npm install gulp-imagemin
-
> optipng-bin@3.0.2 postinstall /Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ⚠ Invalid non-string/buffer chunk
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:95:10)
    at DestroyableTransform.<anonymous> (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:54:10)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:460:10)
    at emitReadable (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:454:7)
    at readableAddChunk (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:209:11)

> gifsicle@3.0.1 postinstall /Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ Invalid non-string/buffer chunk
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:95:10)
    at DestroyableTransform.<anonymous> (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:54:10)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:460:10)
    at emitReadable (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:454:7)
    at readableAddChunk (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:209:11)

> jpegtran-bin@3.0.5 postinstall /Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ Invalid non-string/buffer chunk
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:95:10)
    at DestroyableTransform.<anonymous> (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:54:10)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:460:10)
    at emitReadable (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:454:7)
    at readableAddChunk (/Users/daniel/Projects/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:209:11)
gulp-imagemin@2.3.0 ../node_modules/gulp-imagemin
├── plur@1.0.0
├── object-assign@3.0.0
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── through2-concurrent@1.1.0 (through2@2.0.0)
├── pretty-bytes@2.0.1 (get-stdin@4.0.1, number-is-nan@1.0.0, meow@3.4.2)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, minimist@1.2.0, vinyl@0.5.3, lodash.template@3.6.2, multipipe@0.1.2, through2@2.0.0, dateformat@1.0.11)
└── imagemin@3.2.0 (get-stdin@4.0.1, path-exists@1.0.0, optional@0.1.3, buffer-to-vinyl@1.0.1, concat-stream@1.5.0, stream-combiner2@1.1.0, through2@0.6.5, meow@3.4.2, vinyl-fs@1.0.0, imagemin-svgo@4.1.2, imagemin-optipng@4.3.0, imagemin-gifsicle@4.2.0, imagemin-jpegtran@4.3.1)
```

**Comment by shinnn** [comment] 2015-10-16 23:27
Duplicate of https://github.com/imagemin/imagemin/issues/127

**Closed by shinnn** 2015-10-16 23:27 UTC
