### ISSUE TITLE
optimizationLevel does't work

### ISSUE THREAD

**Issue by vopjie** [sindresorhus/gulp-imagemin#219] opened 2016-10-11 03:30 UTC
here is my code
![image](https://cloud.githubusercontent.com/assets/9351855/19257907/089ad7b2-8fa6-11e6-9502-7767c51f2e8b.png)

**Comment by sindresorhus** [comment] 2016-10-11 07:00
Duplicate of https://github.com/sindresorhus/gulp-imagemin/issues/213#issuecomment-249374686.

**Closed by sindresorhus** 2016-10-11 07:00 UTC
