### ISSUE TITLE
Missing dependency 'imagemin-gifsicle' when using YARN

### ISSUE THREAD

**Issue by italodr** [sindresorhus/gulp-imagemin#226] opened 2016-10-17 09:06 UTC
```
module.js:442
    throw err;
    ^

Error: Cannot find module 'imagemin-gifsicle'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇/node_modules/gulp-imagemin/index.js:8:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by kevva** [comment] 2016-10-17 09:11
Duplicate of https://github.com/sindresorhus/gulp-imagemin/issues/221.

**Closed by kevva** 2016-10-17 09:11 UTC
