### ISSUE TITLE
Console log doesn't tell me which files are optimised

### ISSUE THREAD

**Issue by darrenhaken** [sindresorhus/gulp-imagemin#129] opened 2015-09-10 15:22 UTC
When using gulp-imagemin it printed out to the console which files it optimised and by how much.
However I've just ran it again and it's only telling me the number of files optimised and the total saving.

Is this a feature change or am I doing something wrong?

**Comment by sindresorhus** [comment] 2015-09-10 15:28
Duplicate of #108.

**Closed by sindresorhus** 2015-09-10 15:28 UTC

**Comment by darrenhaken** [comment] 2015-09-10 15:30
Thanks! Strange I don't recall having to use --verbose last time.
Has this been changed in the package?

I appreciate the speedy response!
